# Generated by Django 4.2.2 on 2023-06-14 18:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('iin', models.IntegerField()),
                ('cost_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('quantity_sold', models.IntegerField(default=0)),
                ('selling_price', models.IntegerField()),
                ('profit_earned', models.IntegerField()),
                ('revenue', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('order_cost', models.IntegerField()),
                ('order_date', models.DateTimeField(default=datetime.datetime(2023, 6, 14, 23, 55, 41, 93709))),
                ('is_received', models.BooleanField(default=False)),
                ('is_cancel', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.inventory')),
            ],
        ),
    ]
