# Generated by Django 4.2.2 on 2023-06-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_alter_orders_order_date_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='iin',
            field=models.CharField(max_length=15, unique=True, verbose_name='IIN'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='profit_earned',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='revenue',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default='2023-06-17 21:54:30'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(verbose_name='2023:06:17 21:54:30'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(check=models.Q(('cost_price__gte', 0)), name='positive_price'),
        ),
    ]
